version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=knowyourselves
      - POSTGRES_PASSWORD=thisisasecurepassword
      - POSTGRES_DB=expressify-api
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: